language: node_js
cache:
  directories:
  - $HOME/.npm
notifications:
  email: false
node_js: 8

install: npm install

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/
